# Generated by Django 5.1.5 on 2025-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, verbose_name='Key')),
                ('value', models.CharField(max_length=256, verbose_name='Value')),
                ('env_type', models.CharField(choices=[('DEV', 'Development'), ('TEST', 'Testing'), ('PROD', 'Production')], default='DEV', max_length=4, verbose_name='Environment')),
                ('author_id', models.CharField(max_length=256, verbose_name='Author ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project ID')),
            ],
        ),
    ]
