name: Remove outdated packages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: "ghcr.io/phantomleii/envyper-*"
          exclude-tags: dev,latest,pr*
          keep-n-tagged: 10
