name: CD

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/phantomleii/${{ github.event.repository.name }}-api:latest, ghcr.io/phantomleii/${{ github.event.repository.name }}-api:${{ github.sha }}

      - name: Build Web Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ghcr.io/phantomleii/${{ github.event.repository.name }}-web:latest, ghcr.io/phantomleii/${{ github.event.repository.name }}-web:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push API to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://lebea@envyper.lebogangphoshoko.tech:22/api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          deploy_docker_image: ghcr.io/phantomleii/${{ github.event.repository.name }}-api:latest

      - name: Push Web to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://lebea@envyper.lebogangphoshoko.tech:22/00-default"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          deploy_docker_image: ghcr.io/phantomleii/${{ github.event.repository.name }}-web:latest
