name: "Build Test & Deploy To Dokku App"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/phantomleii/${{ github.event.repository.name }}-api:latest, ghcr.io/phantomleii/${{ github.event.repository.name }}-api:${{ github.sha }}
          context: .
          file: apps/api/Dockerfile

      - name: Build and Push Web Client
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/phantomleii/${{ github.event.repository.name }}-web:latest, ghcr.io/phantomleii/${{ github.event.repository.name }}-web:${{ github.sha }}
          context: .
          file: apps/web/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H evyper.lebogangphoshoko.tech >> ~/.ssh/known_hosts

      - name: Push API to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://azureuser@evyper.lebogangphoshoko.tech:22/api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/phantomleii/${{ github.event.repository.name }}-api:${{ github.sha }}

      - name: Push Web to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://azureuser@evyper.lebogangphoshoko.tech:22/00-default"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/phantomleii/${{ github.event.repository.name }}-web:${{ github.sha }}
