name: "Build Test & Deploy To Dokku App"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.event.repository.owner }}/${{ github.event.repository.name }}-api:latest, ghcr.io/${{ github.event.repository.owner }}/${{ github.event.repository.name }}-api:${{ github.sha }}
          context: .
          file: apps/api/Dockerfile

      - name: Build and Push Web Client
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ vars.USERNAME }}/${{ github.event.repository.name }}-web:latest, ghcr.io/${{ vars.USERNAME }}/${{ github.event.repository.name }}-web:${{ github.sha }}
          context: .
          file: apps/web/Dockerfile
