name: Server CI

on:
  push:
    branches: [main]

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://testuser:test658user@localhost:5432/envyper_test_db
      DEBUG: 1
      ALLOWED_HOSTS: localhost,127.0.0.1
      SECRET_KEY: secret-key
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      JWT_SIGNING_KEY: jwt-signing-key
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: test658user
          POSTGRES_DB: envyper_test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.4
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: python3 apps/server/manage.py migrate && pnpm test

      - name: Run migrations
        run: python3 app/server/manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          ALLOWED_HOSTS: ${{ secrets.SECRET_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
