name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Package Manger
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
